### ISSUE TITLE
Mod does not work with 1.3

### ISSUE THREAD

**Issue by AlanKertz** [emipa606/BestMix#4]
Mod has no effect in 1.3 due to changes in bill logic.

**Comment by emipa606** [comment]
Yes, there is a notice about it on the modpage.

**Comment by AlanKertz** [comment]
I was hoping the issue being open would attract help to fix the issue, I've seen the post on the forum. The Issue is still valid, seems odd to close it.

**Comment by emipa606** [comment]
Ok

**Comment by AlanKertz** [comment]
Looks like this got fixed!

**Comment by emipa606** [comment]
Yea, it got solved in #5 
Forgot this was still open
